spring:
  application:
    name: huava
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/huava?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: huava
    password: eFS0H6_0_pkVm__o
  jackson:
    time-zone: GMT+8
  redis:
    redisson:
      file: classpath:redisson-config.yaml
  cache:
    type: redis
    redis:
      cache-null-values: true
      # 在 RedisConfig.java 中用到，单位是分钟
      time-to-live: 1440

server:
  port: 22345

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.huava: debug
    com.baomidou.mybatisplus.core.executor.BaseExecutor: trace

project:
  jwt_key_base64: JsbZtEZD+oB3sMEnfbmFuqiBFGpNofZkNHTOeuXqPi8=
  # 用于在线验证码， 详情见 https://www.mxnzp.com/doc/detail?id=24
  mxnzp_roll_api:
    # mxnzp APP_ID 和 APP_SECRET 路径，可以是相对路径也可以是绝对路径
    # 相对的是用户的家(home)目录 (如 Windows 下的超级管理员对应了 C:\Users\Administrator )
    # 本来这里可以直接存值的，但考虑到每个项目都应该自己去申请，我不想暴露自己的信息，所以还是存到文件里
    app_id_path: .huava/mxnzp_roll_api/app_id
    app_secret_path: .huava/mxnzp_roll_api/app_secret
  attachment:
    # 存储附件的路径，可以是相对路径或绝对路径
    # 相对的是用户的家(home)目录 (如 Windows 下的超级管理员对应了 C:\Users\Administrator )
    path: .huava/attachment
    # 使用哪个服务类来处理附件上传， 必须继承 BaseUploadService 类
    handle_class: cn.huava.common.service.attachment.UploadToLocalServiceImpl
  # api 权限校验的范围，有两种取值: "all" 或 "main"
  # "all" 表示所有 API 都将被校验，也意味着每个 API 都应该在 sys_perm 表中注册
  # "main" 表示只有以下增删改查的接口才会被校验： ".../create", ".../delete", ".../update", ".../page"
  api_auth_range: main


